name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    env:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      DEBIAN_FRONTEND: noninteractive
      
    steps:
    - name: Install Packages
      run: |
        sudo -E apt-get update  -y
        sudo NEEDRESTART_SUSPEND=1 apt-get install  -y libpam0g-dev libssl-dev
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose --release
    
## upload as artifact
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: target/release/libpam_rssh.so
